### ISSUE TITLE
US2

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Anrii-PM#3]
# Value proposition

As a user I want to see in each project a list of tasks that it has

## Description

![image](https://github.com/AndryBasaraba/Anrii-PM/assets/135517142/37369445-72ee-4802-920c-71af15a92021)

## Acceptance criteria

- [ ] When user click on the project it expands, when user click again on the project it collapses

## Tasks

- [ ] Create branch 
- [ ] Create a new component that will accept a list of tasks from the project and generate it
- [ ] Create a handler that, when pressed, expands and collapses an element with tasks

Size: M

**Comment by CJAkkuec** [comment]
Looking good!
Just a small note:

> As a user I want to see in each project a list of tasks that it has

The value proposition needs a little more work.
Maybe something like

> As a user I want to be able to access each project's tasks via a collapsible element so that I have an organized overview of all projects and their respective tasks.

**Comment by AndryBasaraba** [comment]
agree . Much more informative now. Thanks
