### ISSUE TITLE
US3

### ISSUE THREAD

**Issue by AndryBasaraba** [AndryBasaraba/Anrii-PM#4]
# Value proposition

As a User I can add a new task to the main list

## Description

![image](https://github.com/AndryBasaraba/Anrii-PM/assets/135517142/8ec10ee1-2e61-4079-8247-2dcc41c83160)

## Acceptance criteria

- [ ] when submit is clicked, data is added to the form and automatically return to the main page
- [ ] when adding a list of tasks to the form separated by commas, they are split and transformed into an array of tasks

## Tasks

- [ ] Create branch feature/projects-add
- [ ] Create a new page  localhost:3000/new
- [ ] Create navigation
- [ ] Create a new form page with four fields
- [ ] Create submit button

Size: L

**Comment by CJAkkuec** [comment]
I think the value proposition needs to better describe the benefit of the feature, I also think you're confusing projects and tasks. Clearly you want to be able to add another **project**, _but why_?

The acceptance criteria are a little too bare bones.
Maybe add something that describes how the inputs (title, size, due by, tasks) should behave.

> when adding a list of tasks to the form separated by commas, they are split and transformed into an array of tasks

This isn't an acceptance criteria, because the user has no idea whether the string of all tasks was split into individual strings. That would be a developer task stated at the bottom of the user story.

A plausible acceptance criteria though would be to include that the tasks input includes a placeholder note that reminds the user to separate the individual tasks with a comma.

I've taken the liberty to amend your tasks, as well.
 > Create branch feature/project-form
> Create a new page /new-project
> ~~Create navigation~~

A navigation is not part of the user story as depicted in the wireframe.
The wireframes also display a button that allows the user to add a new project which essentially is required on the project overview page, but not on the page rendering the form. For now you may want to include a back button on the form page that routes back to the overview page.
> Create a new form component with four input fields
> Create a submit button
> Implement logic that handles the submission event and routes back to the overview page

**Comment by AndryBasaraba** [comment]
I have corrected according to your comments. Please check

**Comment by HannesOster** [comment]
Hey Andry,
Looks good, but there is still something you left out of CJ´s comments. 
I would change the from "create a new page/project" to 
"create a new page". Also you could for example mention, how the page should be called and maybe the general function of the page.  :)

The tasks generally could be a little more detailed. What happens pressing the submit button? where is the data saved?

**Comment by AndryBasaraba** [comment]
Hi Hannes,

As for the name of the new page, I already called it that, its function is intertwined with the name, namely adding a new project to the list of projects.

What happens pressing the submit button?  I answered this question in Acceptance criteria

added a way to store data

**Comment by Charlotte-Ketteler** [comment]
LGTM. :)
